name: CI

on:
  push:
    branches: 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello github action ${{ github.event.action }}
    - name: Run a multi-line script
      run: |
        echo Add other action to build,
        echo test, and deploy your project.
    - uses: .github/workflows/pr
